import { useScroll } from 'framer-motion';
// @mui
import Box from '@mui/material/Box';
// components
import { Grid, Typography } from '@mui/material';
import ScrollProgress from 'src/components/scroll-progress';
import { useSettingsContext } from 'src/components/settings';
import { useRouter } from 'src/routes/hook';
import { paths } from 'src/routes/paths';
import BrandsSummary from '../brand-summary';
//

// ----------------------------------------------------------------------
const brands = [
  {
    id: 1,
    name: 'Levis',
    description: 'Clothing brand',
    isActive: false,
    address: {
      country: 'India',
      city: 'NASHIK',
      zip: '422003',
      streetAddress: '08- PETH ROAD',
    },
    paymentInfo: {
      accountHolderName: 'suyog waghere',
      accountHolderEmail: 'suyogwaghere99@gmail.com',
      accountHolderContactNo: '9878998780',
      bankName: 'HDFC',
      accountNumber: '457812457845',
    },
    socials: {
      website: 'https://www.website.com/caitlyn.kerluke',
      facebook: 'https://www.facebook.com/thenehanirwal',
      instagram: 'https://www.instagram.com/thenehanirwal',
      youtube: 'https://www.youtube.com/thenehanirwal',
      twitter: '',
    },
    profileImg: 'http://localhost:3000/files/20231224T140929427Z_aaimages_0.png',
    coverImage: 'http://localhost:3000/files/20231224T140929450Z_wall.jpg',
    createdAt: '2023-12-25T01:16:23.000Z',
    updatedAt: '2023-12-26T19:46:09.000Z',
    userId: 4,
    user: {
      id: 4,
      name: 'atharva',
      email: 'atharva@gmail.com',
      password: '$2a$10$pLQkXPWMga1.rHIAorCGquUwZZXtYXUmxAD2FhhqLgjLfGAmZd98i',
      contactNo: '9877899879',
      permissions: ['brand'],
      createdAt: '2023-12-24T06:43:54.000Z',
      updatedAt: '2023-12-28T09:37:05.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 2,
    name: 'Nike',
    description: 'Sportswear brand',
    isActive: true,
    address: {
      country: 'USA',
      city: 'Portland',
      zip: '97209',
      streetAddress: '1234 SW Nike Ave',
    },
    paymentInfo: {
      accountHolderName: 'John Doe',
      accountHolderEmail: 'john.doe@nike.com',
      accountHolderContactNo: '1234567890',
      bankName: 'Bank of America',
      accountNumber: '123456789012',
    },
    socials: {
      website: 'https://www.nike.com',
      facebook: 'https://www.facebook.com/nike',
      instagram: 'https://www.instagram.com/nike',
      youtube: 'https://www.youtube.com/nike',
      twitter: 'https://twitter.com/nike',
    },
    profileImg: 'https://example.com/nike-profile.jpg',
    coverImage: 'https://example.com/nike-cover.jpg',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    userId: 5,
    user: {
      id: 5,
      name: 'Jane Doe',
      email: 'jane.doe@nike.com',
      password: '$2a$10$...',
      contactNo: '9876543210',
      permissions: ['brand'],
      createdAt: '2024-01-01T12:00:00.000Z',
      updatedAt: '2024-01-01T12:00:00.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 1,
    name: 'Levis',
    description: 'Clothing brand',
    isActive: false,
    address: {
      country: 'India',
      city: 'NASHIK',
      zip: '422003',
      streetAddress: '08- PETH ROAD',
    },
    paymentInfo: {
      accountHolderName: 'suyog waghere',
      accountHolderEmail: 'suyogwaghere99@gmail.com',
      accountHolderContactNo: '9878998780',
      bankName: 'HDFC',
      accountNumber: '457812457845',
    },
    socials: {
      website: 'https://www.website.com/caitlyn.kerluke',
      facebook: 'https://www.facebook.com/thenehanirwal',
      instagram: 'https://www.instagram.com/thenehanirwal',
      youtube: 'https://www.youtube.com/thenehanirwal',
      twitter: '',
    },
    profileImg: 'http://localhost:3000/files/20231224T140929427Z_aaimages_0.png',
    coverImage: 'http://localhost:3000/files/20231224T140929450Z_wall.jpg',
    createdAt: '2023-12-25T01:16:23.000Z',
    updatedAt: '2023-12-26T19:46:09.000Z',
    userId: 4,
    user: {
      id: 4,
      name: 'atharva',
      email: 'atharva@gmail.com',
      password: '$2a$10$pLQkXPWMga1.rHIAorCGquUwZZXtYXUmxAD2FhhqLgjLfGAmZd98i',
      contactNo: '9877899879',
      permissions: ['brand'],
      createdAt: '2023-12-24T06:43:54.000Z',
      updatedAt: '2023-12-28T09:37:05.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 2,
    name: 'Nike',
    description: 'Sportswear brand',
    isActive: true,
    address: {
      country: 'USA',
      city: 'Portland',
      zip: '97209',
      streetAddress: '1234 SW Nike Ave',
    },
    paymentInfo: {
      accountHolderName: 'John Doe',
      accountHolderEmail: 'john.doe@nike.com',
      accountHolderContactNo: '1234567890',
      bankName: 'Bank of America',
      accountNumber: '123456789012',
    },
    socials: {
      website: 'https://www.nike.com',
      facebook: 'https://www.facebook.com/nike',
      instagram: 'https://www.instagram.com/nike',
      youtube: 'https://www.youtube.com/nike',
      twitter: 'https://twitter.com/nike',
    },
    profileImg: 'https://example.com/nike-profile.jpg',
    coverImage: 'https://example.com/nike-cover.jpg',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    userId: 5,
    user: {
      id: 5,
      name: 'Jane Doe',
      email: 'jane.doe@nike.com',
      password: '$2a$10$...',
      contactNo: '9876543210',
      permissions: ['brand'],
      createdAt: '2024-01-01T12:00:00.000Z',
      updatedAt: '2024-01-01T12:00:00.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 1,
    name: 'Levis',
    description: 'Clothing brand',
    isActive: false,
    address: {
      country: 'India',
      city: 'NASHIK',
      zip: '422003',
      streetAddress: '08- PETH ROAD',
    },
    paymentInfo: {
      accountHolderName: 'suyog waghere',
      accountHolderEmail: 'suyogwaghere99@gmail.com',
      accountHolderContactNo: '9878998780',
      bankName: 'HDFC',
      accountNumber: '457812457845',
    },
    socials: {
      website: 'https://www.website.com/caitlyn.kerluke',
      facebook: 'https://www.facebook.com/thenehanirwal',
      instagram: 'https://www.instagram.com/thenehanirwal',
      youtube: 'https://www.youtube.com/thenehanirwal',
      twitter: '',
    },
    profileImg: 'http://localhost:3000/files/20231224T140929427Z_aaimages_0.png',
    coverImage: 'http://localhost:3000/files/20231224T140929450Z_wall.jpg',
    createdAt: '2023-12-25T01:16:23.000Z',
    updatedAt: '2023-12-26T19:46:09.000Z',
    userId: 4,
    user: {
      id: 4,
      name: 'atharva',
      email: 'atharva@gmail.com',
      password: '$2a$10$pLQkXPWMga1.rHIAorCGquUwZZXtYXUmxAD2FhhqLgjLfGAmZd98i',
      contactNo: '9877899879',
      permissions: ['brand'],
      createdAt: '2023-12-24T06:43:54.000Z',
      updatedAt: '2023-12-28T09:37:05.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 2,
    name: 'Nike',
    description: 'Sportswear brand',
    isActive: true,
    address: {
      country: 'USA',
      city: 'Portland',
      zip: '97209',
      streetAddress: '1234 SW Nike Ave',
    },
    paymentInfo: {
      accountHolderName: 'John Doe',
      accountHolderEmail: 'john.doe@nike.com',
      accountHolderContactNo: '1234567890',
      bankName: 'Bank of America',
      accountNumber: '123456789012',
    },
    socials: {
      website: 'https://www.nike.com',
      facebook: 'https://www.facebook.com/nike',
      instagram: 'https://www.instagram.com/nike',
      youtube: 'https://www.youtube.com/nike',
      twitter: 'https://twitter.com/nike',
    },
    profileImg: 'https://example.com/nike-profile.jpg',
    coverImage: 'https://example.com/nike-cover.jpg',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    userId: 5,
    user: {
      id: 5,
      name: 'Jane Doe',
      email: 'jane.doe@nike.com',
      password: '$2a$10$...',
      contactNo: '9876543210',
      permissions: ['brand'],
      createdAt: '2024-01-01T12:00:00.000Z',
      updatedAt: '2024-01-01T12:00:00.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 1,
    name: 'Levis',
    description: 'Clothing brand',
    isActive: false,
    address: {
      country: 'India',
      city: 'NASHIK',
      zip: '422003',
      streetAddress: '08- PETH ROAD',
    },
    paymentInfo: {
      accountHolderName: 'suyog waghere',
      accountHolderEmail: 'suyogwaghere99@gmail.com',
      accountHolderContactNo: '9878998780',
      bankName: 'HDFC',
      accountNumber: '457812457845',
    },
    socials: {
      website: 'https://www.website.com/caitlyn.kerluke',
      facebook: 'https://www.facebook.com/thenehanirwal',
      instagram: 'https://www.instagram.com/thenehanirwal',
      youtube: 'https://www.youtube.com/thenehanirwal',
      twitter: '',
    },
    profileImg: 'http://localhost:3000/files/20231224T140929427Z_aaimages_0.png',
    coverImage: 'http://localhost:3000/files/20231224T140929450Z_wall.jpg',
    createdAt: '2023-12-25T01:16:23.000Z',
    updatedAt: '2023-12-26T19:46:09.000Z',
    userId: 4,
    user: {
      id: 4,
      name: 'atharva',
      email: 'atharva@gmail.com',
      password: '$2a$10$pLQkXPWMga1.rHIAorCGquUwZZXtYXUmxAD2FhhqLgjLfGAmZd98i',
      contactNo: '9877899879',
      permissions: ['brand'],
      createdAt: '2023-12-24T06:43:54.000Z',
      updatedAt: '2023-12-28T09:37:05.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 2,
    name: 'Nike',
    description: 'Sportswear brand',
    isActive: true,
    address: {
      country: 'USA',
      city: 'Portland',
      zip: '97209',
      streetAddress: '1234 SW Nike Ave',
    },
    paymentInfo: {
      accountHolderName: 'John Doe',
      accountHolderEmail: 'john.doe@nike.com',
      accountHolderContactNo: '1234567890',
      bankName: 'Bank of America',
      accountNumber: '123456789012',
    },
    socials: {
      website: 'https://www.nike.com',
      facebook: 'https://www.facebook.com/nike',
      instagram: 'https://www.instagram.com/nike',
      youtube: 'https://www.youtube.com/nike',
      twitter: 'https://twitter.com/nike',
    },
    profileImg: 'https://example.com/nike-profile.jpg',
    coverImage: 'https://example.com/nike-cover.jpg',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    userId: 5,
    user: {
      id: 5,
      name: 'Jane Doe',
      email: 'jane.doe@nike.com',
      password: '$2a$10$...',
      contactNo: '9876543210',
      permissions: ['brand'],
      createdAt: '2024-01-01T12:00:00.000Z',
      updatedAt: '2024-01-01T12:00:00.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 1,
    name: 'Levis',
    description: 'Clothing brand',
    isActive: false,
    address: {
      country: 'India',
      city: 'NASHIK',
      zip: '422003',
      streetAddress: '08- PETH ROAD',
    },
    paymentInfo: {
      accountHolderName: 'suyog waghere',
      accountHolderEmail: 'suyogwaghere99@gmail.com',
      accountHolderContactNo: '9878998780',
      bankName: 'HDFC',
      accountNumber: '457812457845',
    },
    socials: {
      website: 'https://www.website.com/caitlyn.kerluke',
      facebook: 'https://www.facebook.com/thenehanirwal',
      instagram: 'https://www.instagram.com/thenehanirwal',
      youtube: 'https://www.youtube.com/thenehanirwal',
      twitter: '',
    },
    profileImg: 'http://localhost:3000/files/20231224T140929427Z_aaimages_0.png',
    coverImage: 'http://localhost:3000/files/20231224T140929450Z_wall.jpg',
    createdAt: '2023-12-25T01:16:23.000Z',
    updatedAt: '2023-12-26T19:46:09.000Z',
    userId: 4,
    user: {
      id: 4,
      name: 'atharva',
      email: 'atharva@gmail.com',
      password: '$2a$10$pLQkXPWMga1.rHIAorCGquUwZZXtYXUmxAD2FhhqLgjLfGAmZd98i',
      contactNo: '9877899879',
      permissions: ['brand'],
      createdAt: '2023-12-24T06:43:54.000Z',
      updatedAt: '2023-12-28T09:37:05.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 2,
    name: 'Nike',
    description: 'Sportswear brand',
    isActive: true,
    address: {
      country: 'USA',
      city: 'Portland',
      zip: '97209',
      streetAddress: '1234 SW Nike Ave',
    },
    paymentInfo: {
      accountHolderName: 'John Doe',
      accountHolderEmail: 'john.doe@nike.com',
      accountHolderContactNo: '1234567890',
      bankName: 'Bank of America',
      accountNumber: '123456789012',
    },
    socials: {
      website: 'https://www.nike.com',
      facebook: 'https://www.facebook.com/nike',
      instagram: 'https://www.instagram.com/nike',
      youtube: 'https://www.youtube.com/nike',
      twitter: 'https://twitter.com/nike',
    },
    profileImg: 'https://example.com/nike-profile.jpg',
    coverImage: 'https://example.com/nike-cover.jpg',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    userId: 5,
    user: {
      id: 5,
      name: 'Jane Doe',
      email: 'jane.doe@nike.com',
      password: '$2a$10$...',
      contactNo: '9876543210',
      permissions: ['brand'],
      createdAt: '2024-01-01T12:00:00.000Z',
      updatedAt: '2024-01-01T12:00:00.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 1,
    name: 'Levis',
    description: 'Clothing brand',
    isActive: false,
    address: {
      country: 'India',
      city: 'NASHIK',
      zip: '422003',
      streetAddress: '08- PETH ROAD',
    },
    paymentInfo: {
      accountHolderName: 'suyog waghere',
      accountHolderEmail: 'suyogwaghere99@gmail.com',
      accountHolderContactNo: '9878998780',
      bankName: 'HDFC',
      accountNumber: '457812457845',
    },
    socials: {
      website: 'https://www.website.com/caitlyn.kerluke',
      facebook: 'https://www.facebook.com/thenehanirwal',
      instagram: 'https://www.instagram.com/thenehanirwal',
      youtube: 'https://www.youtube.com/thenehanirwal',
      twitter: '',
    },
    profileImg: 'http://localhost:3000/files/20231224T140929427Z_aaimages_0.png',
    coverImage: 'http://localhost:3000/files/20231224T140929450Z_wall.jpg',
    createdAt: '2023-12-25T01:16:23.000Z',
    updatedAt: '2023-12-26T19:46:09.000Z',
    userId: 4,
    user: {
      id: 4,
      name: 'atharva',
      email: 'atharva@gmail.com',
      password: '$2a$10$pLQkXPWMga1.rHIAorCGquUwZZXtYXUmxAD2FhhqLgjLfGAmZd98i',
      contactNo: '9877899879',
      permissions: ['brand'],
      createdAt: '2023-12-24T06:43:54.000Z',
      updatedAt: '2023-12-28T09:37:05.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 2,
    name: 'Nike',
    description: 'Sportswear brand',
    isActive: true,
    address: {
      country: 'USA',
      city: 'Portland',
      zip: '97209',
      streetAddress: '1234 SW Nike Ave',
    },
    paymentInfo: {
      accountHolderName: 'John Doe',
      accountHolderEmail: 'john.doe@nike.com',
      accountHolderContactNo: '1234567890',
      bankName: 'Bank of America',
      accountNumber: '123456789012',
    },
    socials: {
      website: 'https://www.nike.com',
      facebook: 'https://www.facebook.com/nike',
      instagram: 'https://www.instagram.com/nike',
      youtube: 'https://www.youtube.com/nike',
      twitter: 'https://twitter.com/nike',
    },
    profileImg: 'https://example.com/nike-profile.jpg',
    coverImage: 'https://example.com/nike-cover.jpg',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    userId: 5,
    user: {
      id: 5,
      name: 'Jane Doe',
      email: 'jane.doe@nike.com',
      password: '$2a$10$...',
      contactNo: '9876543210',
      permissions: ['brand'],
      createdAt: '2024-01-01T12:00:00.000Z',
      updatedAt: '2024-01-01T12:00:00.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 1,
    name: 'Levis',
    description: 'Clothing brand',
    isActive: false,
    address: {
      country: 'India',
      city: 'NASHIK',
      zip: '422003',
      streetAddress: '08- PETH ROAD',
    },
    paymentInfo: {
      accountHolderName: 'suyog waghere',
      accountHolderEmail: 'suyogwaghere99@gmail.com',
      accountHolderContactNo: '9878998780',
      bankName: 'HDFC',
      accountNumber: '457812457845',
    },
    socials: {
      website: 'https://www.website.com/caitlyn.kerluke',
      facebook: 'https://www.facebook.com/thenehanirwal',
      instagram: 'https://www.instagram.com/thenehanirwal',
      youtube: 'https://www.youtube.com/thenehanirwal',
      twitter: '',
    },
    profileImg: 'http://localhost:3000/files/20231224T140929427Z_aaimages_0.png',
    coverImage: 'http://localhost:3000/files/20231224T140929450Z_wall.jpg',
    createdAt: '2023-12-25T01:16:23.000Z',
    updatedAt: '2023-12-26T19:46:09.000Z',
    userId: 4,
    user: {
      id: 4,
      name: 'atharva',
      email: 'atharva@gmail.com',
      password: '$2a$10$pLQkXPWMga1.rHIAorCGquUwZZXtYXUmxAD2FhhqLgjLfGAmZd98i',
      contactNo: '9877899879',
      permissions: ['brand'],
      createdAt: '2023-12-24T06:43:54.000Z',
      updatedAt: '2023-12-28T09:37:05.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 2,
    name: 'Nike',
    description: 'Sportswear brand',
    isActive: true,
    address: {
      country: 'USA',
      city: 'Portland',
      zip: '97209',
      streetAddress: '1234 SW Nike Ave',
    },
    paymentInfo: {
      accountHolderName: 'John Doe',
      accountHolderEmail: 'john.doe@nike.com',
      accountHolderContactNo: '1234567890',
      bankName: 'Bank of America',
      accountNumber: '123456789012',
    },
    socials: {
      website: 'https://www.nike.com',
      facebook: 'https://www.facebook.com/nike',
      instagram: 'https://www.instagram.com/nike',
      youtube: 'https://www.youtube.com/nike',
      twitter: 'https://twitter.com/nike',
    },
    profileImg: 'https://example.com/nike-profile.jpg',
    coverImage: 'https://example.com/nike-cover.jpg',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    userId: 5,
    user: {
      id: 5,
      name: 'Jane Doe',
      email: 'jane.doe@nike.com',
      password: '$2a$10$...',
      contactNo: '9876543210',
      permissions: ['brand'],
      createdAt: '2024-01-01T12:00:00.000Z',
      updatedAt: '2024-01-01T12:00:00.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 1,
    name: 'Levis',
    description: 'Clothing brand',
    isActive: false,
    address: {
      country: 'India',
      city: 'NASHIK',
      zip: '422003',
      streetAddress: '08- PETH ROAD',
    },
    paymentInfo: {
      accountHolderName: 'suyog waghere',
      accountHolderEmail: 'suyogwaghere99@gmail.com',
      accountHolderContactNo: '9878998780',
      bankName: 'HDFC',
      accountNumber: '457812457845',
    },
    socials: {
      website: 'https://www.website.com/caitlyn.kerluke',
      facebook: 'https://www.facebook.com/thenehanirwal',
      instagram: 'https://www.instagram.com/thenehanirwal',
      youtube: 'https://www.youtube.com/thenehanirwal',
      twitter: '',
    },
    profileImg: 'http://localhost:3000/files/20231224T140929427Z_aaimages_0.png',
    coverImage: 'http://localhost:3000/files/20231224T140929450Z_wall.jpg',
    createdAt: '2023-12-25T01:16:23.000Z',
    updatedAt: '2023-12-26T19:46:09.000Z',
    userId: 4,
    user: {
      id: 4,
      name: 'atharva',
      email: 'atharva@gmail.com',
      password: '$2a$10$pLQkXPWMga1.rHIAorCGquUwZZXtYXUmxAD2FhhqLgjLfGAmZd98i',
      contactNo: '9877899879',
      permissions: ['brand'],
      createdAt: '2023-12-24T06:43:54.000Z',
      updatedAt: '2023-12-28T09:37:05.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 2,
    name: 'Nike',
    description: 'Sportswear brand',
    isActive: true,
    address: {
      country: 'USA',
      city: 'Portland',
      zip: '97209',
      streetAddress: '1234 SW Nike Ave',
    },
    paymentInfo: {
      accountHolderName: 'John Doe',
      accountHolderEmail: 'john.doe@nike.com',
      accountHolderContactNo: '1234567890',
      bankName: 'Bank of America',
      accountNumber: '123456789012',
    },
    socials: {
      website: 'https://www.nike.com',
      facebook: 'https://www.facebook.com/nike',
      instagram: 'https://www.instagram.com/nike',
      youtube: 'https://www.youtube.com/nike',
      twitter: 'https://twitter.com/nike',
    },
    profileImg: 'https://example.com/nike-profile.jpg',
    coverImage: 'https://example.com/nike-cover.jpg',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    userId: 5,
    user: {
      id: 5,
      name: 'Jane Doe',
      email: 'jane.doe@nike.com',
      password: '$2a$10$...',
      contactNo: '9876543210',
      permissions: ['brand'],
      createdAt: '2024-01-01T12:00:00.000Z',
      updatedAt: '2024-01-01T12:00:00.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 1,
    name: 'Levis',
    description: 'Clothing brand',
    isActive: false,
    address: {
      country: 'India',
      city: 'NASHIK',
      zip: '422003',
      streetAddress: '08- PETH ROAD',
    },
    paymentInfo: {
      accountHolderName: 'suyog waghere',
      accountHolderEmail: 'suyogwaghere99@gmail.com',
      accountHolderContactNo: '9878998780',
      bankName: 'HDFC',
      accountNumber: '457812457845',
    },
    socials: {
      website: 'https://www.website.com/caitlyn.kerluke',
      facebook: 'https://www.facebook.com/thenehanirwal',
      instagram: 'https://www.instagram.com/thenehanirwal',
      youtube: 'https://www.youtube.com/thenehanirwal',
      twitter: '',
    },
    profileImg: 'http://localhost:3000/files/20231224T140929427Z_aaimages_0.png',
    coverImage: 'http://localhost:3000/files/20231224T140929450Z_wall.jpg',
    createdAt: '2023-12-25T01:16:23.000Z',
    updatedAt: '2023-12-26T19:46:09.000Z',
    userId: 4,
    user: {
      id: 4,
      name: 'atharva',
      email: 'atharva@gmail.com',
      password: '$2a$10$pLQkXPWMga1.rHIAorCGquUwZZXtYXUmxAD2FhhqLgjLfGAmZd98i',
      contactNo: '9877899879',
      permissions: ['brand'],
      createdAt: '2023-12-24T06:43:54.000Z',
      updatedAt: '2023-12-28T09:37:05.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 2,
    name: 'Nike',
    description: 'Sportswear brand',
    isActive: true,
    address: {
      country: 'USA',
      city: 'Portland',
      zip: '97209',
      streetAddress: '1234 SW Nike Ave',
    },
    paymentInfo: {
      accountHolderName: 'John Doe',
      accountHolderEmail: 'john.doe@nike.com',
      accountHolderContactNo: '1234567890',
      bankName: 'Bank of America',
      accountNumber: '123456789012',
    },
    socials: {
      website: 'https://www.nike.com',
      facebook: 'https://www.facebook.com/nike',
      instagram: 'https://www.instagram.com/nike',
      youtube: 'https://www.youtube.com/nike',
      twitter: 'https://twitter.com/nike',
    },
    profileImg: 'https://example.com/nike-profile.jpg',
    coverImage: 'https://example.com/nike-cover.jpg',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    userId: 5,
    user: {
      id: 5,
      name: 'Jane Doe',
      email: 'jane.doe@nike.com',
      password: '$2a$10$...',
      contactNo: '9876543210',
      permissions: ['brand'],
      createdAt: '2024-01-01T12:00:00.000Z',
      updatedAt: '2024-01-01T12:00:00.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 1,
    name: 'Levis',
    description: 'Clothing brand',
    isActive: false,
    address: {
      country: 'India',
      city: 'NASHIK',
      zip: '422003',
      streetAddress: '08- PETH ROAD',
    },
    paymentInfo: {
      accountHolderName: 'suyog waghere',
      accountHolderEmail: 'suyogwaghere99@gmail.com',
      accountHolderContactNo: '9878998780',
      bankName: 'HDFC',
      accountNumber: '457812457845',
    },
    socials: {
      website: 'https://www.website.com/caitlyn.kerluke',
      facebook: 'https://www.facebook.com/thenehanirwal',
      instagram: 'https://www.instagram.com/thenehanirwal',
      youtube: 'https://www.youtube.com/thenehanirwal',
      twitter: '',
    },
    profileImg: 'http://localhost:3000/files/20231224T140929427Z_aaimages_0.png',
    coverImage: 'http://localhost:3000/files/20231224T140929450Z_wall.jpg',
    createdAt: '2023-12-25T01:16:23.000Z',
    updatedAt: '2023-12-26T19:46:09.000Z',
    userId: 4,
    user: {
      id: 4,
      name: 'atharva',
      email: 'atharva@gmail.com',
      password: '$2a$10$pLQkXPWMga1.rHIAorCGquUwZZXtYXUmxAD2FhhqLgjLfGAmZd98i',
      contactNo: '9877899879',
      permissions: ['brand'],
      createdAt: '2023-12-24T06:43:54.000Z',
      updatedAt: '2023-12-28T09:37:05.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 2,
    name: 'Nike',
    description: 'Sportswear brand',
    isActive: true,
    address: {
      country: 'USA',
      city: 'Portland',
      zip: '97209',
      streetAddress: '1234 SW Nike Ave',
    },
    paymentInfo: {
      accountHolderName: 'John Doe',
      accountHolderEmail: 'john.doe@nike.com',
      accountHolderContactNo: '1234567890',
      bankName: 'Bank of America',
      accountNumber: '123456789012',
    },
    socials: {
      website: 'https://www.nike.com',
      facebook: 'https://www.facebook.com/nike',
      instagram: 'https://www.instagram.com/nike',
      youtube: 'https://www.youtube.com/nike',
      twitter: 'https://twitter.com/nike',
    },
    profileImg: 'https://example.com/nike-profile.jpg',
    coverImage: 'https://example.com/nike-cover.jpg',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    userId: 5,
    user: {
      id: 5,
      name: 'Jane Doe',
      email: 'jane.doe@nike.com',
      password: '$2a$10$...',
      contactNo: '9876543210',
      permissions: ['brand'],
      createdAt: '2024-01-01T12:00:00.000Z',
      updatedAt: '2024-01-01T12:00:00.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 1,
    name: 'Levis',
    description: 'Clothing brand',
    isActive: false,
    address: {
      country: 'India',
      city: 'NASHIK',
      zip: '422003',
      streetAddress: '08- PETH ROAD',
    },
    paymentInfo: {
      accountHolderName: 'suyog waghere',
      accountHolderEmail: 'suyogwaghere99@gmail.com',
      accountHolderContactNo: '9878998780',
      bankName: 'HDFC',
      accountNumber: '457812457845',
    },
    socials: {
      website: 'https://www.website.com/caitlyn.kerluke',
      facebook: 'https://www.facebook.com/thenehanirwal',
      instagram: 'https://www.instagram.com/thenehanirwal',
      youtube: 'https://www.youtube.com/thenehanirwal',
      twitter: '',
    },
    profileImg: 'http://localhost:3000/files/20231224T140929427Z_aaimages_0.png',
    coverImage: 'http://localhost:3000/files/20231224T140929450Z_wall.jpg',
    createdAt: '2023-12-25T01:16:23.000Z',
    updatedAt: '2023-12-26T19:46:09.000Z',
    userId: 4,
    user: {
      id: 4,
      name: 'atharva',
      email: 'atharva@gmail.com',
      password: '$2a$10$pLQkXPWMga1.rHIAorCGquUwZZXtYXUmxAD2FhhqLgjLfGAmZd98i',
      contactNo: '9877899879',
      permissions: ['brand'],
      createdAt: '2023-12-24T06:43:54.000Z',
      updatedAt: '2023-12-28T09:37:05.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 2,
    name: 'Nike',
    description: 'Sportswear brand',
    isActive: true,
    address: {
      country: 'USA',
      city: 'Portland',
      zip: '97209',
      streetAddress: '1234 SW Nike Ave',
    },
    paymentInfo: {
      accountHolderName: 'John Doe',
      accountHolderEmail: 'john.doe@nike.com',
      accountHolderContactNo: '1234567890',
      bankName: 'Bank of America',
      accountNumber: '123456789012',
    },
    socials: {
      website: 'https://www.nike.com',
      facebook: 'https://www.facebook.com/nike',
      instagram: 'https://www.instagram.com/nike',
      youtube: 'https://www.youtube.com/nike',
      twitter: 'https://twitter.com/nike',
    },
    profileImg: 'https://example.com/nike-profile.jpg',
    coverImage: 'https://example.com/nike-cover.jpg',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    userId: 5,
    user: {
      id: 5,
      name: 'Jane Doe',
      email: 'jane.doe@nike.com',
      password: '$2a$10$...',
      contactNo: '9876543210',
      permissions: ['brand'],
      createdAt: '2024-01-01T12:00:00.000Z',
      updatedAt: '2024-01-01T12:00:00.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 1,
    name: 'Levis',
    description: 'Clothing brand',
    isActive: false,
    address: {
      country: 'India',
      city: 'NASHIK',
      zip: '422003',
      streetAddress: '08- PETH ROAD',
    },
    paymentInfo: {
      accountHolderName: 'suyog waghere',
      accountHolderEmail: 'suyogwaghere99@gmail.com',
      accountHolderContactNo: '9878998780',
      bankName: 'HDFC',
      accountNumber: '457812457845',
    },
    socials: {
      website: 'https://www.website.com/caitlyn.kerluke',
      facebook: 'https://www.facebook.com/thenehanirwal',
      instagram: 'https://www.instagram.com/thenehanirwal',
      youtube: 'https://www.youtube.com/thenehanirwal',
      twitter: '',
    },
    profileImg: 'http://localhost:3000/files/20231224T140929427Z_aaimages_0.png',
    coverImage: 'http://localhost:3000/files/20231224T140929450Z_wall.jpg',
    createdAt: '2023-12-25T01:16:23.000Z',
    updatedAt: '2023-12-26T19:46:09.000Z',
    userId: 4,
    user: {
      id: 4,
      name: 'atharva',
      email: 'atharva@gmail.com',
      password: '$2a$10$pLQkXPWMga1.rHIAorCGquUwZZXtYXUmxAD2FhhqLgjLfGAmZd98i',
      contactNo: '9877899879',
      permissions: ['brand'],
      createdAt: '2023-12-24T06:43:54.000Z',
      updatedAt: '2023-12-28T09:37:05.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  {
    id: 2,
    name: 'Nike',
    description: 'Sportswear brand',
    isActive: true,
    address: {
      country: 'USA',
      city: 'Portland',
      zip: '97209',
      streetAddress: '1234 SW Nike Ave',
    },
    paymentInfo: {
      accountHolderName: 'John Doe',
      accountHolderEmail: 'john.doe@nike.com',
      accountHolderContactNo: '1234567890',
      bankName: 'Bank of America',
      accountNumber: '123456789012',
    },
    socials: {
      website: 'https://www.nike.com',
      facebook: 'https://www.facebook.com/nike',
      instagram: 'https://www.instagram.com/nike',
      youtube: 'https://www.youtube.com/nike',
      twitter: 'https://twitter.com/nike',
    },
    profileImg: 'https://example.com/nike-profile.jpg',
    coverImage: 'https://example.com/nike-cover.jpg',
    createdAt: '2024-01-01T12:00:00.000Z',
    updatedAt: '2024-01-01T12:00:00.000Z',
    userId: 5,
    user: {
      id: 5,
      name: 'Jane Doe',
      email: 'jane.doe@nike.com',
      password: '$2a$10$...',
      contactNo: '9876543210',
      permissions: ['brand'],
      createdAt: '2024-01-01T12:00:00.000Z',
      updatedAt: '2024-01-01T12:00:00.000Z',
      isActive: true,
      otp: 'string',
      otpExpireAt: 'string',
    },
  },
  // Add 10 more brand objects here with similar structures...
];
// ----------------------------------------------------------------------

export default function BrandsView() {
  const { scrollYProgress } = useScroll();
  const settings = useSettingsContext();
  //   const { brands } = useGetBrands();
  const router = useRouter();
  return (
    <>
      <ScrollProgress scrollYProgress={scrollYProgress} />
      <Box
        // my={10}
        mx={{ xs: `5%`, md: `12%` }}
        style={{
          borderRadius: `36px`,
          border: `1px solid rgba(0, 0, 0, 0.30)`,

          // marginLeft: { xs: `5%`, md: `20%` },

          // marginRight: { xs: `5%`, md: `20%` },
        }}
      >
        <Grid container padding="5%" col>
          <Grid md={12} sm={12} xs={12} row>
            <Typography
              variant="h2"
              style={{
                // fontFamily: 'Dosis',
                fontWeight: '800',
                textTransform: 'uppercase',
                textAlign: 'center',
              }}
            >
              Brands
            </Typography>
          </Grid>
          <Grid>
            {/* <Grid container gap={3}> */}
            <Box display="grid" gap={3}>
              {brands.map((brand) => (
                <Grid item md={3} key={brand?.name}>
                  <BrandsSummary
                    title={brand?.name}
                    description={brand?.description}
                    contactNo={brand?.user?.contactNo}
                    isActive={brand?.isActive}
                    address={brand?.address}
                    color="primary"
                    icon={
                      <img alt="icon" src={`${brand?.profileImg}`} style={{ borderRadius: 100 }} />
                    }
                    onClick={(e) => {
                      e.preventDefault();
                      if (
                        router &&
                        paths &&
                        paths.brand_dashboard &&
                        paths.brand_dashboard.brands &&
                        paths.brand_dashboard.brands.details &&
                        brand &&
                        brand.id
                      ) {
                        localStorage.setItem('brandId', brand?.id);

                        router.push(paths.brand_dashboard.brands.dashboard(brand?.id));
                      } else {
                        console.error('One or more required objects are undefined');
                      }
                    }}
                  />
                </Grid>
              ))}
            </Box>
            {/* </Grid> */}
          </Grid>
        </Grid>
      </Box>
    </>
  );
}
